language: python
python:
  - "2.6"
  - "2.7"

env:
  - REQUIREMENTS="Django<1.5 django-discover-runner"
  - REQUIREMENTS="Django<1.6 django-discover-runner"
  - REQUIREMENTS="Django<1.7"

before_install:
  - sudo apt-get -y install libcairo2-dev
  - mkdir -p storage/log/webapp
  - mkdir -p storage/ceres
  - cd webapp

install:
  - pip install https://github.com/graphite-project/ceres/tarball/master
  - pip install $REQUIREMENTS
  - pip install whisper django-tagging pytz pyparsing==1.5.7 http://cairographics.org/releases/py2cairo-1.8.10.tar.gz

script:
  - PYTHONPATH=. python graphite/manage.py test --settings=tests.settings
